# Generated by Django 5.2.13 on 2026-04-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
